### ISSUE TITLE
Fix #! line to use python2

### ISSUE THREAD

**Issue by ctb** [ged-lab/khmer#794]
All these scripts reference `/usr/bin/env python`, and not `/usr/bin/env python2`, in the shebang line.

```
calc-best-assembly.py
calc-error-profile.py
normalize-by-align.py
read_aligner.py
slice-reads-by-coverage.py
```

Ref #53

**Comment by Echelon9** [comment]
Claiming this issue to work on.

**Comment by Echelon9** [comment]
Ready for review

**Comment by mr-c** [comment]
Looks like @alameldin already started on this in #813 an hour before @Echelon9 did and then closed his pull request. Oops!

I guess I'll merge @Echelon9 's pull request since it is complete.

A reminder to claim issues before you start working on them (See: http://khmer.readthedocs.org/en/latest/dev/getting-started.html#claiming-an-issue-and-starting-to-develop )
